### PR TITLE
Move Gitian build docs out of project root

### PR DESCRIPTION
**Pull request by mitchellcash**

### CODE REVIEW

**Comment by cevap** [comment]
any explanation for deletion? We just added them.

**Comment by cevap** [comment]
lets move them probably would be better, why deleting?

**Comment by mitchellcash** [comment]
@cevap the gitian-building doc already exists in doc/gitian-building.md and is the most up to date version of the guide.

I think the files placed in root were mistakenly put there.

**Comment by cevap** [comment]
ok, I see now, probably you are right, would need to check new documentation if it is used anywhere, but yes, that is projects root, not documents root. I think you are right.

**Comment by cevap** [comment]
ok, it happened [here](https://github.com/cevap/ion/commit/11c941a14c8128a601a84ed2e83a7a189e8c4716), those images are already part of [./doc/gitian-building] folder. Thanks for the catchup, you are right.

**Pull request merged**
