### PR TITLE
Changes to gitian-building.md file

### PR DESCRIPTION
**Pull request by ckti**
Changes to gitian-building.md file to reflect new VirtualBox building and increase of disk size

### CODE REVIEW

**Comment by aspaas** [comment]
Great idea @ckti, to simplify and streamline the gitian build process. 
(I accepted the screenshot-PR, but the new images do not show yet in this version. Also, some minor changes to the text are definitely needed. Perhaps it's better to create a branch for this change?)

Some questions, please @ckti @cevap @mitchellcash : discuss!

1) Bitcoin's gitian process creates a VM inside a VM. This updated process skips that, and directly wants you to create the final VM. Any idea why Bitcoin chose the VM-in-a-VM-approach? Any reason why we should deviate from that?

2) The process of creating a VM and converting the qcow2 files might be correct, but it's hard to understand - especially for anybody who hasn't done it before. Perhaps more explanation on that?

3) Will all of this work on Windows and OSX? Do we need to explain the steps for that?

Thanks

**Comment by aspaas** [comment]
OK first answer from myself ;)
Apparently Gitian can only be used with debian/ubuntu based hosts, and can only use debian/ubuntu guests. 
Windows has the Linux subsystem now, which is currently (and probably in the future too) the only way to build Ion Core from Windows. It should be possible to run Gitian from there.
(Not sure about OSX.)
Most likely, Bitcoin used the VM-in-a-VM-approach because at that time, there was no way to run Gitian from Windows. But that's just a guess.. I might ask this to the Bitcoin Stackexchange.

References:
https://blog.torproject.org/deterministic-builds-part-two-technical-details
https://bitcoin.stackexchange.com/questions/46220/are-there-alternatives-to-gitian

**Comment by ckti** [comment]
Q2) Tried to make it so than creating the VM followed the steps for creating the qcow2 image. If a bit more clarity is needed it's not a problem to change the doc around.    Tried to make it read as step-by-step guide.
Q3) It _should_ work on OSX as that is a linux distro as well and the qcow2 can be created and converted.  Not sure about Windows -- afaict the qcow2 could be converted and the result run on Windows VM. Have tried running the pure qcow2 in VM but no real results to give atm.

**Comment by ckti** [comment]
Have thought of a different way of approaching this document without losing the "Bitcoin VM in a VM" method.   I leave that part in there and simply add to the document after the KVM install as "Virtual Box Method #2".  Starting up my markdown atm.

**Comment by ckti** [comment]
Have thought of a different way of approaching this document without losing the "Bitcoin VM in a VM" method.   I leave that part in there and simply add to the document after the initial gitian install as "Virtual Box Method #2".

**Comment by cevap** [comment]
Ok, I agree on that. You mean method number two, not guidelines/policies from ticket #2 ?

**Comment by ckti** [comment]
yes method number 2.  Will add in to the document rather than remove the entire vm -> vm bitcoin method.  people familiar with bitcoin will still be happy and those who want to try something new and different will be happy also.

**Comment by cevap** [comment]
How much bigger is it?

We can offer it also as alternative method. I am sure, those who do not manage to get it with current would still prefer more the ability for alternative instead of nothing.

**Comment by ckti** [comment]
20-30 lines plus 3 images

**Comment by cevap** [comment]
We have with 2.1.6.3 ion-cli and ion-tx, I am building now vm's with KVM to test scripts, but it will take some time for me to review them. 

In general, I want at the end ability to put and add also autoupload to launchpad process, nobody said that only we have repository, it is good if our can be used and we are able to offer one, however, other who do build would have that way also a possibilty for own repository and its maintenance.

**Comment by cevap** [comment]
that is not a lot bigger :+1: , let's add it after the test that it works without bigger issues, @aspaas is busy next few days and will not be able to test, testing it now....

**Comment by ckti** [comment]
yes, have gitian images that i'm in the process of setting up launchpad repo with ion-cli and ion-tx in startup/shutdown through build VM method 2

**Pull request merged**
