### PR TITLE
Remove redundant/duplicate declarations.

### PR DESCRIPTION
**Pull request by FornaxA**
See https://github.com/cevap/ion/issues/102
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/cevap/ion/pull/103%23issuecomment-449461802%22%2C%20%22https%3A//github.com/cevap/ion/pull/103%23issuecomment-449464888%22%2C%20%22https%3A//github.com/cevap/ion/pull/103%23issuecomment-449464916%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/cevap/ion/pull/103%23issuecomment-449461802%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22this%20pull%20includes%20also%20autocombine%20change%3A%20https%3A//github.com/cevap/ion/pull/103/files%23diff-e75eff0ce0dde388eddbe3173db85bd4%5Cr%5Cn%5Cr%5Cnthere%20was%20always%20discussion%20about%20it%2C%20actually%20I%20dislike%20if%20thats%20disabled%2C%20can%20you%20change%20this%20back%20in%20your%20branch%20so%20that%20I%20can%20merge%20this%20pull%3F%22%2C%20%22created_at%22%3A%20%222018-12-21T18%3A21%3A26Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars3.githubusercontent.com/u/24996551%3Fv%3D4%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/cevap%22%7D%7D%2C%20%7B%22body%22%3A%20%22I%20removed%20autocombine%20and%20can%20merge%20now.%20%40FornaxA%20We%20should%20create%20separate%20issue%20for%20autocombine%2C%20feel%20free%20to%20reopen.%22%2C%20%22created_at%22%3A%20%222018-12-21T18%3A34%3A13Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars3.githubusercontent.com/u/24996551%3Fv%3D4%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/cevap%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222018-12-21T18%3A34%3A21Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars3.githubusercontent.com/u/24996551%3Fv%3D4%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/cevap%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%2C%20%22approved%22%3A%20%7B%22https%3A//github.com/cevap%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars3.githubusercontent.com/u/24996551%3Fv%3D4%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>

<a href='https://github.com/cevap'></a>

- [x] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/cevap/ion/pull/103#issuecomment-449461802'>General Comment</a></b>
- <a href='https://github.com/cevap'></a> this pull includes also autocombine change: https://github.com/cevap/ion/pull/103/files#diff-e75eff0ce0dde388eddbe3173db85bd4
there was always discussion about it, actually I dislike if thats disabled, can you change this back in your branch so that I can merge this pull?
- <a href='https://github.com/cevap'></a> I removed autocombine and can merge now. @FornaxA We should create separate issue for autocombine, feel free to reopen.

<a href='https://www.codereviewhub.com/cevap/ion/pull/103?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/cevap/ion/pull/103?approve=1'></a>&nbsp;<a href='https://www.codereviewhub.com/cevap/ion/pull/103?approve=0'></a>&nbsp;<a href='https://github.com/cevap/ion/pull/103'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by cevap** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/cevap/ion/pull/103'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by cevap** [comment]
this pull includes also autocombine change: https://github.com/cevap/ion/pull/103/files#diff-e75eff0ce0dde388eddbe3173db85bd4

there was always discussion about it, actually I dislike if thats disabled, can you change this back in your branch so that I can merge this pull?

**Comment by cevap** [comment]
I removed autocombine and can merge now. @FornaxA We should create separate issue for autocombine, feel free to reopen.

**Comment by cevap** [comment]
:shipit:

**Comment by Kokary** [comment]
Ok fair enough, it should have been in a different PR anyway.. But I thought it was a trivial change.
Anyway, ok for me to keep it like that.

**Comment by cevap** [comment]
yes, we can add autocombine pull, but autocombine should be enabled, would be my opinion. Disabling autocombine would require somebody to ensure creation of xion's of all denominations as otherwise users will experience problems in releasing them due to not being confirmed.

Maybe we should add info/warning about autocombine to the text where data dir is created when wallet is launched for the first time.

**Pull request merged**
