### PR TITLE
Set locks on cs_wallet for SelectCoinsMasternode() which is called by…

### PR DESCRIPTION
**Pull request by FornaxA**
… `masternode outputs`

See https://github.com/cevap/ion/issues/126
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/cevap/ion/pull/127%23issuecomment-449653178%22%2C%20%22https%3A//github.com/cevap/ion/pull/127%23issuecomment-449732414%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/cevap/ion/pull/127%23issuecomment-449653178%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22Lock%20it%20first%2C%20makes%20sense%22%2C%20%22created_at%22%3A%20%222018-12-23T17%3A50%3A26Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars1.githubusercontent.com/u/7046769%3Fv%3D4%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/ckti%22%7D%7D%2C%20%7B%22body%22%3A%20%22compiled%20from%20master%20and%20can%20confirm%20it%22%2C%20%22created_at%22%3A%20%222018-12-24T13%3A08%3A51Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars3.githubusercontent.com/u/24996551%3Fv%3D4%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/cevap%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [ ] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/cevap/ion/pull/127#issuecomment-449653178'>General Comment</a></b>
- <a href='https://github.com/ckti'></a> Lock it first, makes sense
- <a href='https://github.com/cevap'></a> compiled from master and can confirm it

<a href='https://www.codereviewhub.com/cevap/ion/pull/127?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/cevap/ion/pull/127?approve=1'></a>&nbsp;<a href='https://github.com/cevap/ion/pull/127'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by cevap** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/cevap/ion/pull/127'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by ckti** [comment]
Lock it first, makes sense

**Comment by cevap** [comment]
compiled from master and can confirm it

**Comment by cevap** [comment]
:shipit:

**Pull request merged**
