### PR TITLE
ref: #13 - Cleanup oem branding

### PR DESCRIPTION
**Pull request by cevap**
removed almost all occurencies of bitcoin, links kept as well as copyrights, big commit
<a href='#crh-start'></a><a href='#crh-data-%7B%22approved%22%3A%20%7B%22https%3A//github.com/cevap%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars3.githubusercontent.com/u/24996551%3Fv%3D4%22%7D%7D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/cevap/ion/pull/16%23issuecomment-377590803%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222018-03-30T18%3A30%3A13Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars3.githubusercontent.com/u/24996551%3Fv%3D4%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/cevap%22%7D%7D%2C%20%7B%22body%22%3A%20%22%40cevap%3A%20same%20in%20this%20file%3A%20https%3A//github.com/cevap/ion/pull/16/commits/ea0d23f586af811f2228ffc2a33a47199e306ab3%23diff-7ec3c68a81efff79b6ca22ac1f1eabba%5Cr%5Cn%60%60%60%5Cr%5Cn%2A%20We%20are%20%7E100%20times%20smaller%20then%20ion%20now%20%282015-06-23%29%2C%20set%20minRelayTxFee%20only%2010%20times%20higher%5Cr%5Cn%2A%20so%20it%27s%20still%2010%20times%20lower%20comparing%20to%20ion.%5Cr%5Cn%60%60%60%22%2C%20%22created_at%22%3A%20%222018-03-30T18%3A39%3A52Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars2.githubusercontent.com/u/25762277%3Fv%3D4%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/FornaxA%22%7D%7D%2C%20%7B%22body%22%3A%20%22%40cevap%20%3A%20this%20one%20too%3A%5Cr%5Cnhttps%3A//github.com/cevap/ion/blob/ea0d23f586af811f2228ffc2a33a47199e306ab3/src/pow.cpp%23L70%5Cr%5Cn%60Ion%20can%20wait%202%20weeks%20between%20updates%20but%20no%20altcoin%20can.%60%5Cr%5Cn%5Cr%5Cnhttps%3A//github.com/cevap/ion/blob/ea0d23f586af811f2228ffc2a33a47199e306ab3/src/wallet.cpp%23L50%5Cr%5Cn%60We%20are%20%7E100%20times%20smaller%20then%20ion%20now%20%282015-06-23%29%2C%20set%20minTxFee%2010%20times%20higher%60%5Cr%5Cn%5Cr%5CnAlso%3A%20did%20you%20check%20for%20%28case%20sensitive%29%20%27Bitcoin%27%3F%22%2C%20%22created_at%22%3A%20%222018-03-30T18%3A52%3A11Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars2.githubusercontent.com/u/25762277%3Fv%3D4%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/FornaxA%22%7D%7D%2C%20%7B%22body%22%3A%20%22mac%20build%20failed%20on%20travis%3A%5Cr%5Cn%60%60%60%5Cr%5Cn%2B%20Deploying%20frameworks%20%2B%5Cr%5CnWarning%3A%20Could%20not%20find%20any%20external%20frameworks%20to%20deploy%20in%20dist/Ion-Qt.app.%5Cr%5CnWarning%3A%20Could%20not%20detect%20Qt%27s%20path%2C%20skipping%20plugin%20deployment%21%5Cr%5Cn%2B%20Installing%20qt.conf%20%2B%5Cr%5Cn%2B%20Adding%20Qt%20translations%20%2B%5Cr%5Cn%2B%20Done%20%2B%5Cr%5Cn/bin/mkdir%20-p%20dist/.background%5Cr%5Cn/usr/bin/tiffcp%20-c%20none%20dpi36.background.tiff%20dpi72.background.tiff%20dist/.background/background.tiff%5Cr%5Cn/usr/bin/python3.4%20contrib/macdeploy/custom_dsstore.py%20%5C%22dist/.DS_Store%5C%22%20%5C%22Ion-Core%5C%22%5Cr%5CnTraceback%20%28most%20recent%20call%20last%29%3A%5Cr%5Cn%20%20File%20%5C%22contrib/macdeploy/custom_dsstore.py%5C%22%2C%20line%2046%2C%20in%20%3Cmodule%3E%5Cr%5Cn%20%20%20%20alias%20%3D%20Alias.from_bytes%28icvp%5B%27backgroundImageAlias%27%5D%29%5Cr%5Cn%20%20File%20%5C%22/home/travis/build/cevap/ion/depends/x86_64-apple-darwin11/native/lib/python/dist-packages/mac_alias/alias.py%5C%22%2C%20line%20334%2C%20in%20from_bytes%5Cr%5Cn%20%20%20%20return%20cls._from_fd%28b%29%5Cr%5Cn%20%20File%20%5C%22/home/travis/build/cevap/ion/depends/x86_64-apple-darwin11/native/lib/python/dist-packages/mac_alias/alias.py%5C%22%2C%20line%20320%2C%20in%20_from_fd%5Cr%5Cn%20%20%20%20alias.volume.disk_image_alias%20%3D%20Alias.from_bytes%28value%29%5Cr%5Cn%20%20File%20%5C%22/home/travis/build/cevap/ion/depends/x86_64-apple-darwin11/native/lib/python/dist-packages/mac_alias/alias.py%5C%22%2C%20line%20334%2C%20in%20from_bytes%5Cr%5Cn%20%20%20%20return%20cls._from_fd%28b%29%5Cr%5Cn%20%20File%20%5C%22/home/travis/build/cevap/ion/depends/x86_64-apple-darwin11/native/lib/python/dist-packages/mac_alias/alias.py%5C%22%2C%20line%20279%2C%20in%20_from_fd%5Cr%5Cn%20%20%20%20alias.target.folder_name%20%3D%20value.decode%28%29.replace%28%27/%27%2C%27%3A%27%29%5Cr%5CnUnicodeDecodeError%3A%20%27utf-8%27%20codec%20can%27t%20decode%20byte%200xab%20in%20position%200%3A%20invalid%20start%20byte%5Cr%5Cnmake%3A%20%2A%2A%2A%20%5Bdist/.DS_Store%5D%20Error%201%5Cr%5CnThe%20command%20%5C%22make%20%24MAKEJOBS%20%24GOAL%20%7C%7C%20%28%20echo%20%5C%22Build%20failure.%20Verbose%20build%20follows.%5C%22%20%26%26%20make%20%24GOAL%20V%3D1%20%3B%20false%20%29%5C%22%20exited%20with%201.%5Cr%5Cn0.01s%24%20export%20LD_LIBRARY_PATH%3D%24TRAVIS_BUILD_DIR/depends/%24HOST/lib%5Cr%5CnThe%20command%20%5C%22export%20LD_LIBRARY_PATH%3D%24TRAVIS_BUILD_DIR/depends/%24HOST/lib%5C%22%20exited%20with%200.%5Cr%5Cn0.01s%24%20if%20%5B%20%5C%22%24RUN_TESTS%5C%22%20%3D%20%5C%22true%5C%22%20%5D%3B%20then%20travis_wait%2030%20make%20%24MAKEJOBS%20check%20VERBOSE%3D1%3B%20fi%5Cr%5CnThe%20command%20%5C%22if%20%5B%20%5C%22%24RUN_TESTS%5C%22%20%3D%20%5C%22true%5C%22%20%5D%3B%20then%20travis_wait%2030%20make%20%24MAKEJOBS%20check%20VERBOSE%3D1%3B%20fi%5C%22%20exited%20with%200.%5Cr%5Cncache.2%5Cr%5Cnstore%20build%20cache%5Cr%5Cn0.01s%5Cr%5Cn11.38schange%20detected%20%28content%20changed%2C%20file%20is%20created%2C%20or%20file%20is%20deleted%29%3A%5Cr%5Cn/home/travis/.ccache/0/1/0f029d58bd7226d71c28d759b5082b-6649803.o%5Cr%5Cn/home/travis/.ccache/0/2/0cd207c1388d7977a0f10841ee831b-30334.manifest%5Cr%5Cn/home/travis/.ccache/0/2/7b55e01eb092572039c5e5373cd141-7176097.o%5Cr%5Cn/home/travis/.ccache/0/2/8305f0f317c96dc1c9286ad5322606-13935.manifest%5Cr%5Cn/home/travis/.ccache/0/4/330c39024d2c69773ea59e264842e0-6650.manifest%5Cr%5Cn/home/travis/.ccache/0/5/226671a6e181aeebb216cf208bd34e-8983.manifest%5Cr%5Cn/home/travis/.ccache/0/6/95a09bf102f3aabce8ee7fcc6fac86-5388504.o%5Cr%5Cn/home/travis/.ccache/0/8/4577f1dbe46748db69fd1c51c5dd66-16974.manifest%5Cr%5Cn/home/travis/.ccache/0/8/b6f1e63ffa4563e45ecfea3a21a5c0-6219.manifest%5Cr%5Cn/home/travis/.ccache/0/a/a0b5be8ca4db7301e5a86a42ae4038-5631.manifest%5Cr%5Cn/home/travis/.ccache/0/b/2247ffc8c21c48e0c1e4b46e7e4cbd-5512373.o%5Cr%5Cn/home/travis/.ccache/0/b/90c9f8b634e0ac94073da139dafaed-7246.manifest%5Cr%5Cn/home/travis/.ccache/0/b/adc9f99cda70df259d5d468da01ed7-5956872.o%5Cr%5Cn/home/travis/.ccache/0/b/f4a1958ab9fb73862654b70e8fe349-5571982.o%5Cr%5Cn/home/travis/.ccache/0/b/fd026fd750b640d23%5Cr%5Cn...%5Cr%5Cnchanges%20detected%2C%20packing%20new%20archive%5Cr%5Cn.%5Cr%5Cnuploading%20archive%5Cr%5Cnafter_script.1%5Cr%5Cn0.01s%24%20echo%20%24TRAVIS_COMMIT_RANGE%5Cr%5Cnafter_script.2%5Cr%5Cn0.01s%24%20echo%20%24TRAVIS_COMMIT_LOG%5Cr%5Cn%60%60%60%5Cr%5Cnrebuilding%20it%20to%20see%20it%20was%20just%20on%20travis%22%2C%20%22created_at%22%3A%20%222018-03-30T19%3A06%3A38Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars3.githubusercontent.com/u/24996551%3Fv%3D4%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/cevap%22%7D%7D%2C%20%7B%22body%22%3A%20%22yes%2C%20I%20checkd%2C%20if%20you%20look%20up%2C%20I%20actually%20remove%20them%20all%2C%20its%20fully%20debranded%22%2C%20%22created_at%22%3A%20%222018-03-30T19%3A07%3A41Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars3.githubusercontent.com/u/24996551%3Fv%3D4%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/cevap%22%7D%7D%2C%20%7B%22body%22%3A%20%22https%3A//github.com/cevap/ion/blob/ea0d23f586af811f2228ffc2a33a47199e306ab3/README.md%23our-sources%5Cr%5Cn%60%60%60%5Cr%5Cn%20%201.%20%5BPIVX%5D%28https%3A//github.com/PIVX-Project/PIVX%29%5Cr%5Cn%20%201.%20%5BDASH%5D%28https%3A//github.com/dashpay/dash%29%5Cr%5Cn%20%201.%20%5BBitcoin%5D%28https%3A//github.com/ion/ion%29%5Cr%5Cn%60%60%60%22%2C%20%22created_at%22%3A%20%222018-03-30T19%3A16%3A06Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars2.githubusercontent.com/u/25762277%3Fv%3D4%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/FornaxA%22%7D%7D%2C%20%7B%22body%22%3A%20%22%60UnicodeDecodeError%3A%20%27utf-8%27%20codec%20can%27t%20decode%20byte%200xab%20in%20position%200%3A%20invalid%20start%20byte%60%22%2C%20%22created_at%22%3A%20%222018-03-30T19%3A20%3A18Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars3.githubusercontent.com/u/24996551%3Fv%3D4%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/cevap%22%7D%7D%2C%20%7B%22body%22%3A%20%22https%3A//github.com/cevap/ion/blob/ea0d23f586af811f2228ffc2a33a47199e306ab3/src/qt/ionaddressvalidator.h%23L23%5Cr%5Cn%5Cr%5Cnhttps%3A//github.com/cevap/ion/blob/ea0d23f586af811f2228ffc2a33a47199e306ab3/src/qt/iongui.h%23L43%5Cr%5Cn%5Cr%5Cnhttps%3A//github.com/cevap/ion/blob/ea0d23f586af811f2228ffc2a33a47199e306ab3/src/script/standard.cpp%23L50%5Cr%5Cn%5Cr%5CnThat%27s%20it%20for%20me%21%5Cr%5CnGreat%20job%20%3A%29%22%2C%20%22created_at%22%3A%20%222018-03-30T19%3A20%3A46Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars2.githubusercontent.com/u/25762277%3Fv%3D4%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/FornaxA%22%7D%7D%2C%20%7B%22body%22%3A%20%22applying%20those%20back%2C%20thx%20for%20looking%20up%2C%20this%20part%20is%20boring%22%2C%20%22created_at%22%3A%20%222018-03-30T19%3A59%3A03Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars3.githubusercontent.com/u/24996551%3Fv%3D4%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/cevap%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%2C%20%22processed%22%3A%20%5B%22https%3A//github.com/cevap/ion/pull/16%23issuecomment-377590803%22%2C%20%22https%3A//github.com/cevap/ion/pull/16%23issuecomment-377592999%22%2C%20%22https%3A//github.com/cevap/ion/pull/16%23issuecomment-377595525%22%2C%20%22https%3A//github.com/cevap/ion/pull/16%23issuecomment-377598634%22%2C%20%22https%3A//github.com/cevap/ion/pull/16%23issuecomment-377598859%22%2C%20%22https%3A//github.com/cevap/ion/pull/16%23issuecomment-377600633%22%2C%20%22https%3A//github.com/cevap/ion/pull/16%23issuecomment-377601446%22%2C%20%22https%3A//github.com/cevap/ion/pull/16%23issuecomment-377601550%22%2C%20%22https%3A//github.com/cevap/ion/pull/16%23issuecomment-377609132%22%5D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>

<a href='https://github.com/cevap'></a>

- [ ] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/cevap/ion/pull/16#issuecomment-377590803'>General Comment</a></b>
- <a href='https://github.com/cevap'></a> :shipit:
- <a href='https://github.com/FornaxA'></a> @cevap: same in this file: https://github.com/cevap/ion/pull/16/commits/ea0d23f586af811f2228ffc2a33a47199e306ab3#diff-7ec3c68a81efff79b6ca22ac1f1eabba
```
* We are ~100 times smaller then ion now (2015-06-23), set minRelayTxFee only 10 times higher
* so it's still 10 times lower comparing to ion.
```
- <a href='https://github.com/FornaxA'></a> @cevap : this one too:
https://github.com/cevap/ion/blob/ea0d23f586af811f2228ffc2a33a47199e306ab3/src/pow.cpp#L70
`Ion can wait 2 weeks between updates but no altcoin can.`
https://github.com/cevap/ion/blob/ea0d23f586af811f2228ffc2a33a47199e306ab3/src/wallet.cpp#L50
`We are ~100 times smaller then ion now (2015-06-23), set minTxFee 10 times higher`
Also: did you check for (case sensitive) 'Bitcoin'?
- <a href='https://github.com/cevap'></a> mac build failed on travis:
```
+ Deploying frameworks +
Warning: Could not find any external frameworks to deploy in dist/Ion-Qt.app.
Warning: Could not detect Qt's path, skipping plugin deployment!
+ Installing qt.conf +
+ Adding Qt translations +
+ Done +
/bin/mkdir -p dist/.background
/usr/bin/tiffcp -c none dpi36.background.tiff dpi72.background.tiff dist/.background/background.tiff
/usr/bin/python3.4 contrib/macdeploy/custom_dsstore.py "dist/.DS_Store" "Ion-Core"
Traceback (most recent call last):
File "contrib/macdeploy/custom_dsstore.py", line 46, in <module>
alias = Alias.from_bytes(icvp['backgroundImageAlias'])
File "/home/travis/build/cevap/ion/depends/x86_64-apple-darwin11/native/lib/python/dist-packages/mac_alias/alias.py", line 334, in from_bytes
return cls._from_fd(b)
File "/home/travis/build/cevap/ion/depends/x86_64-apple-darwin11/native/lib/python/dist-packages/mac_alias/alias.py", line 320, in _from_fd
alias.volume.disk_image_alias = Alias.from_bytes(value)
File "/home/travis/build/cevap/ion/depends/x86_64-apple-darwin11/native/lib/python/dist-packages/mac_alias/alias.py", line 334, in from_bytes
return cls._from_fd(b)
File "/home/travis/build/cevap/ion/depends/x86_64-apple-darwin11/native/lib/python/dist-packages/mac_alias/alias.py", line 279, in _from_fd
alias.target.folder_name = value.decode().replace('/',':')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xab in position 0: invalid start byte
make: *** [dist/.DS_Store] Error 1
The command "make $MAKEJOBS $GOAL || ( echo "Build failure. Verbose build follows." && make $GOAL V=1 ; false )" exited with 1.
0.01s$ export LD_LIBRARY_PATH=$TRAVIS_BUILD_DIR/depends/$HOST/lib
The command "export LD_LIBRARY_PATH=$TRAVIS_BUILD_DIR/depends/$HOST/lib" exited with 0.
0.01s$ if [ "$RUN_TESTS" = "true" ]; then travis_wait 30 make $MAKEJOBS check VERBOSE=1; fi
The command "if [ "$RUN_TESTS" = "true" ]; then travis_wait 30 make $MAKEJOBS check VERBOSE=1; fi" exited with 0.
cache.2
store build cache
0.01s
11.38schange detected (content changed, file is created, or file is deleted):
/home/travis/.ccache/0/1/0f029d58bd7226d71c28d759b5082b-6649803.o
/home/travis/.ccache/0/2/0cd207c1388d7977a0f10841ee831b-30334.manifest
/home/travis/.ccache/0/2/7b55e01eb092572039c5e5373cd141-7176097.o
/home/travis/.ccache/0/2/8305f0f317c96dc1c9286ad5322606-13935.manifest
/home/travis/.ccache/0/4/330c39024d2c69773ea59e264842e0-6650.manifest
/home/travis/.ccache/0/5/226671a6e181aeebb216cf208bd34e-8983.manifest
/home/travis/.ccache/0/6/95a09bf102f3aabce8ee7fcc6fac86-5388504.o
/home/travis/.ccache/0/8/4577f1dbe46748db69fd1c51c5dd66-16974.manifest
/home/travis/.ccache/0/8/b6f1e63ffa4563e45ecfea3a21a5c0-6219.manifest
/home/travis/.ccache/0/a/a0b5be8ca4db7301e5a86a42ae4038-5631.manifest
/home/travis/.ccache/0/b/2247ffc8c21c48e0c1e4b46e7e4cbd-5512373.o
/home/travis/.ccache/0/b/90c9f8b634e0ac94073da139dafaed-7246.manifest
/home/travis/.ccache/0/b/adc9f99cda70df259d5d468da01ed7-5956872.o
/home/travis/.ccache/0/b/f4a1958ab9fb73862654b70e8fe349-5571982.o
/home/travis/.ccache/0/b/fd026fd750b640d23
...
changes detected, packing new archive
.
uploading archive
after_script.1
0.01s$ echo $TRAVIS_COMMIT_RANGE
after_script.2
0.01s$ echo $TRAVIS_COMMIT_LOG
```
rebuilding it to see it was just on travis
- <a href='https://github.com/cevap'></a> yes, I checkd, if you look up, I actually remove them all, its fully debranded
- <a href='https://github.com/FornaxA'></a> https://github.com/cevap/ion/blob/ea0d23f586af811f2228ffc2a33a47199e306ab3/README.md#our-sources
```
1. [PIVX](https://github.com/PIVX-Project/PIVX)
1. [DASH](https://github.com/dashpay/dash)
1. [Bitcoin](https://github.com/ion/ion)
```
- <a href='https://github.com/cevap'></a> `UnicodeDecodeError: 'utf-8' codec can't decode byte 0xab in position 0: invalid start byte`
- <a href='https://github.com/FornaxA'></a> https://github.com/cevap/ion/blob/ea0d23f586af811f2228ffc2a33a47199e306ab3/src/qt/ionaddressvalidator.h#L23
https://github.com/cevap/ion/blob/ea0d23f586af811f2228ffc2a33a47199e306ab3/src/qt/iongui.h#L43
https://github.com/cevap/ion/blob/ea0d23f586af811f2228ffc2a33a47199e306ab3/src/script/standard.cpp#L50
That's it for me!
Great job :)
- <a href='https://github.com/cevap'></a> applying those back, thx for looking up, this part is boring

<a href='https://www.codereviewhub.com/cevap/ion/pull/16?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/cevap/ion/pull/16?approve=1'></a>&nbsp;<a href='https://www.codereviewhub.com/cevap/ion/pull/16?approve=0'></a>&nbsp;<a href='https://github.com/cevap/ion/pull/16'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by cevap** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/cevap/ion/pull/16'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by cevap** [comment]
:shipit:

**Comment by FornaxA** [comment]
@cevap: same in this file: https://github.com/cevap/ion/pull/16/commits/ea0d23f586af811f2228ffc2a33a47199e306ab3#diff-7ec3c68a81efff79b6ca22ac1f1eabba
```
* We are ~100 times smaller then ion now (2015-06-23), set minRelayTxFee only 10 times higher
* so it's still 10 times lower comparing to ion.
```

**Comment by FornaxA** [comment]
@cevap : this one too:
https://github.com/cevap/ion/blob/ea0d23f586af811f2228ffc2a33a47199e306ab3/src/pow.cpp#L70
`Ion can wait 2 weeks between updates but no altcoin can.`

https://github.com/cevap/ion/blob/ea0d23f586af811f2228ffc2a33a47199e306ab3/src/wallet.cpp#L50
`We are ~100 times smaller then ion now (2015-06-23), set minTxFee 10 times higher`

Also: did you check for (case sensitive) 'Bitcoin'?

**Comment by cevap** [comment]
mac build failed on travis:
```
+ Deploying frameworks +
Warning: Could not find any external frameworks to deploy in dist/Ion-Qt.app.
Warning: Could not detect Qt's path, skipping plugin deployment!
+ Installing qt.conf +
+ Adding Qt translations +
+ Done +
/bin/mkdir -p dist/.background
/usr/bin/tiffcp -c none dpi36.background.tiff dpi72.background.tiff dist/.background/background.tiff
/usr/bin/python3.4 contrib/macdeploy/custom_dsstore.py "dist/.DS_Store" "Ion-Core"
Traceback (most recent call last):
  File "contrib/macdeploy/custom_dsstore.py", line 46, in <module>
    alias = Alias.from_bytes(icvp['backgroundImageAlias'])
  File "/home/travis/build/cevap/ion/depends/x86_64-apple-darwin11/native/lib/python/dist-packages/mac_alias/alias.py", line 334, in from_bytes
    return cls._from_fd(b)
  File "/home/travis/build/cevap/ion/depends/x86_64-apple-darwin11/native/lib/python/dist-packages/mac_alias/alias.py", line 320, in _from_fd
    alias.volume.disk_image_alias = Alias.from_bytes(value)
  File "/home/travis/build/cevap/ion/depends/x86_64-apple-darwin11/native/lib/python/dist-packages/mac_alias/alias.py", line 334, in from_bytes
    return cls._from_fd(b)
  File "/home/travis/build/cevap/ion/depends/x86_64-apple-darwin11/native/lib/python/dist-packages/mac_alias/alias.py", line 279, in _from_fd
    alias.target.folder_name = value.decode().replace('/',':')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xab in position 0: invalid start byte
make: *** [dist/.DS_Store] Error 1
The command "make $MAKEJOBS $GOAL || ( echo "Build failure. Verbose build follows." && make $GOAL V=1 ; false )" exited with 1.
0.01s$ export LD_LIBRARY_PATH=$TRAVIS_BUILD_DIR/depends/$HOST/lib
The command "export LD_LIBRARY_PATH=$TRAVIS_BUILD_DIR/depends/$HOST/lib" exited with 0.
0.01s$ if [ "$RUN_TESTS" = "true" ]; then travis_wait 30 make $MAKEJOBS check VERBOSE=1; fi
The command "if [ "$RUN_TESTS" = "true" ]; then travis_wait 30 make $MAKEJOBS check VERBOSE=1; fi" exited with 0.
cache.2
store build cache
0.01s
11.38schange detected (content changed, file is created, or file is deleted):
/home/travis/.ccache/0/1/0f029d58bd7226d71c28d759b5082b-6649803.o
/home/travis/.ccache/0/2/0cd207c1388d7977a0f10841ee831b-30334.manifest
/home/travis/.ccache/0/2/7b55e01eb092572039c5e5373cd141-7176097.o
/home/travis/.ccache/0/2/8305f0f317c96dc1c9286ad5322606-13935.manifest
/home/travis/.ccache/0/4/330c39024d2c69773ea59e264842e0-6650.manifest
/home/travis/.ccache/0/5/226671a6e181aeebb216cf208bd34e-8983.manifest
/home/travis/.ccache/0/6/95a09bf102f3aabce8ee7fcc6fac86-5388504.o
/home/travis/.ccache/0/8/4577f1dbe46748db69fd1c51c5dd66-16974.manifest
/home/travis/.ccache/0/8/b6f1e63ffa4563e45ecfea3a21a5c0-6219.manifest
/home/travis/.ccache/0/a/a0b5be8ca4db7301e5a86a42ae4038-5631.manifest
/home/travis/.ccache/0/b/2247ffc8c21c48e0c1e4b46e7e4cbd-5512373.o
/home/travis/.ccache/0/b/90c9f8b634e0ac94073da139dafaed-7246.manifest
/home/travis/.ccache/0/b/adc9f99cda70df259d5d468da01ed7-5956872.o
/home/travis/.ccache/0/b/f4a1958ab9fb73862654b70e8fe349-5571982.o
/home/travis/.ccache/0/b/fd026fd750b640d23
...
changes detected, packing new archive
.
uploading archive
after_script.1
0.01s$ echo $TRAVIS_COMMIT_RANGE
after_script.2
0.01s$ echo $TRAVIS_COMMIT_LOG
```
rebuilding it to see it was just on travis

**Comment by cevap** [comment]
yes, I checkd, if you look up, I actually remove them all, its fully debranded

**Comment by FornaxA** [comment]
https://github.com/cevap/ion/blob/ea0d23f586af811f2228ffc2a33a47199e306ab3/README.md#our-sources
```
  1. [PIVX](https://github.com/PIVX-Project/PIVX)
  1. [DASH](https://github.com/dashpay/dash)
  1. [Bitcoin](https://github.com/ion/ion)
```

**Comment by cevap** [comment]
`UnicodeDecodeError: 'utf-8' codec can't decode byte 0xab in position 0: invalid start byte`

**Comment by FornaxA** [comment]
https://github.com/cevap/ion/blob/ea0d23f586af811f2228ffc2a33a47199e306ab3/src/qt/ionaddressvalidator.h#L23

https://github.com/cevap/ion/blob/ea0d23f586af811f2228ffc2a33a47199e306ab3/src/qt/iongui.h#L43

https://github.com/cevap/ion/blob/ea0d23f586af811f2228ffc2a33a47199e306ab3/src/script/standard.cpp#L50

That's it for me!
Great job :)

**Comment by cevap** [comment]
applying those back, thx for looking up, this part is boring

**Pull request closed without merging**
